apiVersion: batch/v1
kind: Job
metadata:
  name: my-migrate-job
spec:
  template:
    spec:
      containers:
        - name: my-migrate
          image: localhost:5000/django_app:latest
          command: [ "python", "manage.py", "migrate", "--noinput" ]
          envFrom:
            - secretRef:
                name: django-env
      restartPolicy: OnFailure
  backoffLimit: 4