apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: edu-stoic-dubinsky
  labels:
    app: nginx
spec:
  restartPolicy: OnFailure
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
      - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: edu-stoic-dubinsky
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: edu-stoic-dubinsky
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: edu-stoic-dubinsky.sirius-k8s.dvmn.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-loadbalancer
                port:
                  number: 80
  tls:
    - hosts:
        - edu-stoic-dubinsky.sirius-k8s.dvmn.org
