apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: <namespace>
  labels:
    app: django
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: django-deploy
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
        app.kubernetes.io/name: django
        app.kubernetes.io/instance: django-deploy
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - name: django
          image: ultimate1465/django_app:a201b435a6cb31a42067c20df8bbecc2f0c11ac0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: django-env
