apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: edu-stoic-dubinsky
spec:
  volumes:
    - name: pg-root-cert
      secret:
        secretName: root-cert
  containers:
    - name: ubuntu-container
      image: ubuntu:22.04
      command: [ "/bin/sh" ]
      args:
        - -c
        - |
          apt-get update &&
          apt-get install -y postgresql-client &&
          mkdir -p /root/.postgresql &&
          sleep 86400
      volumeMounts:
        - name: pg-root-cert
          mountPath: /root/.postgresql
          readOnly: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"